apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: gohello
        image: jluisalvarez/go_hello:v1
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m